# SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie <jeff@ocjtech.us>
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitignore"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".gitattributes"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "hooks/pre-command-*"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "MIT"
