#!/bin/bash
set
arch="${HOSTTYPE/arm64/aarch64}"
os=$(echo "$OSTYPE" | sed -E 's/darwin[0-9]*/macos/g' | sed 's/-gnu//g')
printf "%s-%s\n" "$arch" "$os"
printf "%s\n" "${BASH_ARGV[0]}"

exec "${BASH_ARGV[0]}-${arch}-${os}"
